apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: microservices
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://user_service:securepassword@postgres-primary.default.svc.cluster.local:5432/user_service_db"
  REDIS_URL: "redis://redis.default.svc.cluster.local:6379"
  JWT_SECRET_KEY: "supersecretfly"
