apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: rideshare
type: Opaque
stringData:
  DATABASE_URL: "${{ secrets.DATABASE_URL }}"
  REDIS_URL: "${{ secrets.REDIS_URL }}"
  JWT_SECRET_KEY: "${{ secrets.JWT_SECRET_KEY }}"
