apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: microservices
type: Opaque
stringData:
  DATABASE_URL: "<REDACTED>"
  REDIS_URL: "<REDACTED>"
  JWT_SECRET_KEY: "<REDACTED>"
