apiVersion: v1
kind: Service
metadata:
  name: user-service       
  namespace: microservices
spec:
  selector:
    app: user-microservice     
  ports:
    - name: http
      port: 8001
      targetPort: 8000
  type: ClusterIP