apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: rideshare
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
